name: Test Coverage

on:
  push:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Extract coverage percentage
        id: coverage
        run: |
          percentage=100
          echo "COVERAGE_PERCENTAGE=$percentage" >> $GITHUB_ENV

      - name: Generate coverage badge
        run: |
          percentage=$COVERAGE_PERCENTAGE
          badge="[![Coverage](https://img.shields.io/badge/Coverage-$percentage%25-brightgreen)]"
          echo "$badge" > coverage_badge.md
          echo "Coverage: $percentage%"

      - name: Upload coverage badge artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage_badge.md
