name: Test Coverage

on:
  push:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Generate badge
        run: node .github/action/generate_badge.js

      - name: Setup GCP_KEY_ACCOUNT
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "teste-ci-key.json"
          encodedString: ${{ secrets.GCP_KEY_ACCOUNT }}

      - name: Upload badge
        run: node .github/action/upload_badge.js
